Task_1_1_1
Mikhail05Evdokimov/OOP pull request #1
Opened 2022-09-21 04:35 UTC by Mikhail05Evdokimov

2022-09-21 06:41 UTC, shadrina requested changes
Назначать ревьюера лучше после того, как билд заработает и все варнинги во вкладке Files changed будут решены.

2022-09-25 15:22 UTC, shadrina requested changes
Билд заработал, но во вкладке Files changed по-прежнему варнинги. + много лишних файлов, которые я просила заигнорить с помощью `.gitignore`

2022-09-28 05:08 UTC, shadrina requested changes
Все то же самое.

2022-10-03 10:23 UTC, shadrina requested changes
Миша, почему опять куча варнингов в файле с тестами?)

2022-10-03 10:28 UTC, Mikhail05Evdokimov commented
Они не убираются
Это ошибка в длине отступа, как я понял. Считаю, что checker на ровном
месте проблему видит

пн, 3 окт. 2022 г., 17:23 Anastasia Shadrina ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Миша, почему опять куча варнингов в файле с тестами?)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail05Evdokimov/OOP/pull/1#pullrequestreview-1128138445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2M52ACMPFREF2Q5RMAMWTWBKX2JANCNFSM6AAAAAAQRVZLQI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 10:51 UTC, shadrina commented
Нет, там не только про отступы. У тебя названия методов в тестах с большой буквы.
А чтобы с отступами было все хорошо, нажми в Идее Ctrl+Alt+L и закоммить.

2022-10-03 10:52 UTC, Mikhail05Evdokimov commented
Понял, исправлю, спасибо.

пн, 3 окт. 2022 г., 17:51 Anastasia Shadrina ***@***.***>:

> Нет, там не только про отступы. У тебя названия методов в тестах с большой
> буквы.
> А чтобы с отступами было все хорошо, нажми в Идее Ctrl+Alt+L и закоммить.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mikhail05Evdokimov/OOP/pull/1#issuecomment-1265265450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2M52EYJ54OGUNBITPUVTDWBK3D5ANCNFSM6AAAAAAQRVZLQI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-05 08:33 UTC, shadrina requested changes

2022-10-05 08:33 UTC, shadrina commented on Task_1_1_1/script.bat
> +jar cf .\make\jar\heapsort.jar -C .\make\bin .
Нет исполнения jar'а командой `java`

2022-10-05 08:33 UTC, shadrina commented on Task_1_1_1/src/main/java/ru/nsu/mevdokimov1/Heapsort.java
> +    public void heapify(int []arr, int n, int i) {
Зачем метод публичный? Он используется за пределами класса?

2022-10-05 08:33 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +    public void simple_test() {
Не понимаю, почему это съел reviewdog, но в Java мы используем camelCase: `simpleTest`

2022-10-05 08:33 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +        ob.sort(arr1);
Зачем нужен объект, если вызываемый метод статический?

2022-10-05 13:48 UTC, Mikhail05Evdokimov commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +    public void simple_test() {
У меня сначала так и называлось. Reviewdog на эти строчки ругался. После переименования в name_test всё стало хорошо

2022-10-05 13:49 UTC, Mikhail05Evdokimov commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +    public void simple_test() {
Сейчас сделал как было - ошибок нет

2022-10-11 18:12 UTC, shadrina approved these changes

2022-10-11 18:12 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +
Коммент обычно располагается прямо над описываемым элементом. Лишние переводы строк не нужны

2022-10-11 18:12 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/mevdokimov1/MyTests.java
> +     * Test number four with empty list.
Не надо писать про номер теста, ненужная информация

2022-10-12 05:47 UTC, merged