Task_2_1_1
Mikhail05Evdokimov/OOP pull request #3
Opened 2023-03-27 14:22 UTC by Mikhail05Evdokimov

2023-03-27 15:36 UTC, Mikhail05Evdokimov commented
Урааа, работает

2023-04-09 12:54 UTC, shadrina requested changes
Добавь еще, пожалуйста, информацию о характеристиках своего процессора и тест дате (объем, какие там числа)

2023-04-09 12:54 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcher.java
> +            int number = arr.remove(0);
А зачем модифицировать контейнер, если тебе нужно только посмотреть?

2023-04-09 12:54 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +                }
Давай вот это вынесем в отдельный метод

2023-04-09 12:54 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +        List<Integer> numbers;
Вот тут надо заприватить и сделать конструктор, который будет инициализировать филд

2023-04-09 12:54 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +        List<Integer> numbers;
Или просто сразу выставлять в `new ArrayList<>()` и добавить сеттер

2023-04-10 14:16 UTC, Mikhail05Evdokimov commented on Task_2_1_1/src/main/java/PrimeSearcher.java
> +            int number = arr.remove(0);
done.

2023-04-10 14:16 UTC, Mikhail05Evdokimov commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +                }
done.

2023-04-10 14:16 UTC, Mikhail05Evdokimov commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +        List<Integer> numbers;
done?

2023-04-10 14:21 UTC, Mikhail05Evdokimov commented
> Добавь еще, пожалуйста, информацию о характеристиках своего процессора и тест дате (объем, какие там числа)

Intel Core i5-3317U CPU 1.70 GHz
4 логических ядра
Входные данные больших тестов отвратительным образом лежат в коде тестов

2023-04-18 17:43 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +        int block = arr.size() / threadsCount;
А будет ли тут все в порядке, если размер массива не кратен кол-ву тредов?

2023-04-18 17:45 UTC, shadrina commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +                }
Мы все же стараемся учиться писать хороший код. В хорошем коде название метода должно говорить о том, что метод делает, а не о том, что злой преподаватель сказал его сделать)

2023-04-20 05:25 UTC, Mikhail05Evdokimov commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +        int block = arr.size() / threadsCount;
Остаток действительно терялся. Теперь блоки на один элемент больше, в последний поток записывается то, что осталось

2023-04-20 05:26 UTC, Mikhail05Evdokimov commented on Task_2_1_1/src/main/java/PrimeSearcherThread.java
> +                }
fixed

2023-04-21 06:48 UTC, shadrina commented
Please fix checkstyle

2023-05-01 13:03 UTC, shadrina reviewed
Подойди пожалуйста на паре завтра

2023-05-08 10:01 UTC, Mikhail05Evdokimov commented
Сделал нормальное считывание из файла и большой тест - график времени работы стал таким, каким примерно и должен быть

2023-05-10 14:03 UTC, shadrina reviewed
Загрузи плиз график как картинку, pptx GitHub не отображает

2023-05-10 14:31 UTC, Mikhail05Evdokimov commented
> Загрузи плиз график как картинку, pptx GitHub не отображает

Загрузил

2023-05-15 11:56 UTC, shadrina approved these changes

2023-05-16 02:03 UTC, merged