Task_1_2_2
Mikhail05Evdokimov/OOP pull request #6
Opened 2022-10-22 13:40 UTC by Mikhail05Evdokimov

2022-10-24 08:55 UTC, Allody22 commented on Task_1_2_2/src/main/java/DeepFirstSearch.java
> +    MyStack<MyTree<T>> stack = new MyStack<>();
Missing a java doc comment

2022-10-24 13:28 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/DeepFirstSearch.java
> +    MyStack<MyTree<T>> stack = new MyStack<>();
fixed

2022-10-24 13:36 UTC, Allody22 approved these changes
Okay

2022-10-24 13:43 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyStack.java
> +import java.util.Arrays;
![yes](https://user-images.githubusercontent.com/91541224/197540148-af7fefc5-75b8-408e-bc4c-8f9b88e7ae9c.jpg)

2022-10-31 13:36 UTC, shadrina requested changes

2022-10-31 13:36 UTC, shadrina commented on Task_1_2_2/src/main/java/BreadthFirstSearch.java
> +public class BreadthFirstSearch<T> implements Iterator<T> {
Это итератор, почему бы не назвать его `BreadthFirstSearchIterator`?

2022-10-31 13:36 UTC, shadrina commented on Task_1_2_2/src/main/java/MyTree.java
> +    public Iterator<T> iterator() {
Еще бы метод `dfsIterator()` увидеть

2022-10-31 13:36 UTC, shadrina commented on Task_1_2_2/src/main/java/MyTree.java
> +    public MyTree<T> add(T childVal) {
В примере задачи используются два разных метода `add`. Вижу только один

2022-10-31 13:36 UTC, shadrina commented on Task_1_2_2/src/main/java/MyTree.java
> +        this.parent = newParent;
Почему вот эта операция не считается модификацией?

2022-10-31 13:57 UTC, shadrina commented
И вопрос: какой процент кода написан самостоятельно?

2022-10-31 14:14 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyTree.java
> +        this.parent = newParent;
Изменение родителя вершины не меняет порядка итерации по дереву, так как по дереву мы ходим сверху вниз и смотрим на детей, а не на родителей. Так что на работу итератора это изменение не влияет, а значит оно безопасно.

2022-10-31 14:17 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyTree.java
> +        this.parent = newParent;
> И вопрос: какой процент кода написан самостоятельно?

Значительный. В реализации Лёши и Артёма заглядывал, но только чтобы иметь представление о том, какие функции нужно реализовывать, и как в целом должно работать дерево с итераторами. А какая часть кода вызывает подозрения??

2022-10-31 14:45 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyTree.java
> +    public MyTree<T> add(T childVal) {
добавил второй

2022-10-31 14:48 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/BreadthFirstSearch.java
> +public class BreadthFirstSearch<T> implements Iterator<T> {
Это итератор для поиска в ширину. Почему бы не назвать его "Поиск в ширину" ?

2022-10-31 14:55 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyTree.java
> +    public Iterator<T> iterator() {
Этот метод должен принимать дерево и возвращать список элементов в порядке итерации?

2022-10-31 16:02 UTC, shadrina commented on Task_1_2_2/src/main/java/MyTree.java
> +        this.parent = newParent;
> Изменение родителя вершины не меняет порядка итерации по дереву

Логически изменение родителя должно быть сопряжено с изменением списка детей => с изменением дерева. Относительно твоей реализации это действительно так. Но как часть публичного контракта, этот метод вводит в заблуждение. Может, его лучше заприватить?

2022-10-31 16:12 UTC, shadrina commented
Вопрос об авторстве - не обвинение, а уточнение. Моя задача - убедиться, что вы понимаете написанное, и я это делаю напрямую, опираясь на честность собеседника. Не нужно обижаться : )

2022-10-31 16:23 UTC, Mikhail05Evdokimov commented on Task_1_2_2/src/main/java/MyTree.java
> +        this.parent = newParent;
с Аргументацией по названию итераторов согласен, исправил. Изменение родителя заприватил. Не совсем понял про второй итератор.

2022-11-02 06:20 UTC, Allody22 approved these changes
approved

2022-11-07 10:30 UTC, shadrina approved these changes

2022-11-08 04:54 UTC, merged