Task_1_2_3
Mikhail05Evdokimov/OOP pull request #7
Opened 2022-11-20 08:18 UTC by Mikhail05Evdokimov

2022-11-20 15:40 UTC, Allody22 reviewed
Небольшие исправления, бегло пробежался по коду

2022-11-20 15:40 UTC, Allody22 commented on Task_1_2_3/src/main/java/Graph.java
> +    public List<Vertex<T>> deykstraAlgorithm(Vertex<T> start) {
Миш, посмотри, **_пожалуйста_**, как на английском эта фамилия пишется и напиши правильно

2022-11-20 15:40 UTC, Allody22 commented on Task_1_2_3/src/test/java/GraphTests.java
> +        Edge<Integer> e1 = new Edge<>(1, v1, v2);
Наверное, стоит добавить считывание из файла, чтобы код выглядел покомпактнее

2022-11-21 06:54 UTC, Mikhail05Evdokimov commented on Task_1_2_3/src/main/java/Graph.java
> +    public List<Vertex<T>> deykstraAlgorithm(Vertex<T> start) {
Исправил.

2022-11-29 12:23 UTC, shadrina requested changes

2022-11-29 12:23 UTC, shadrina commented on Task_1_2_3/src/main/java/Graph.java
> +    }
Почему граф Comparable с таким странным compareTo?

2022-11-29 12:23 UTC, shadrina commented on Task_1_2_3/src/main/java/Graph.java
> +        this.vertexArray.get(from).addWay(edge);
`this.` имеет смысл использовать, когда происходит клэш имен, например, имен филдов и параметров метода. Здесь такого нет, `this.` можно убрать

2022-11-29 12:23 UTC, shadrina commented on Task_1_2_3/src/main/java/Graph.java
> +        this.vertexArray.get(from).addWay(edge);
Наблюдается не только в этой строке, а по всему коду

2022-11-30 06:51 UTC, shadrina approved these changes

2022-11-30 06:59 UTC, merged