Task_1_4_1
Mikhail05Evdokimov/OOP pull request #8
Opened 2022-11-26 07:57 UTC by Mikhail05Evdokimov

2022-11-28 04:44 UTC, Allody22 commented
Миш, у тебя оч много files changed, пофикси плиз

2022-11-28 04:53 UTC, Mikhail05Evdokimov commented
> Миш, у тебя оч много files changed, пофикси плиз

Забыл .gitignore сделать. Исправил.

2022-11-30 14:19 UTC, Mikhail05Evdokimov commented
Конкретизировал исключения.
Заменил конструкции for{ if( ) } на методы stream().

2022-12-08 12:04 UTC, shadrina requested changes
В остальном ок

2022-12-08 12:04 UTC, shadrina commented on Task_1_4_1/src/main/java/RecordBook.java
> +        if (semesters.get(semesterNumber).marks.get(subject) != null) {
Тут надо проверять на null на каждом очередном вызове `get`, не только на последнем. Если `semesters.get(semesterNumber)` даст `null`, все упадет с NPE. Сделай пожалуйста соответствующий тест и поставь тут проверку.

А Идея кстати варнинг тут не рисует?

2022-12-08 12:04 UTC, shadrina commented on Task_1_4_1/src/main/java/RecordBook.java
> +        if (semesters.get(semesterNumber).marks.get(subject) == null) {
Аналогично

2022-12-08 12:04 UTC, shadrina commented on Task_1_4_1/src/main/java/RecordBook.java
> +        semesters.get(semesterNumber).marks.remove(subject);
Аналогично

2022-12-08 12:04 UTC, shadrina commented on Task_1_4_1/src/main/java/RecordBook.java
> +            semesters.get(semesterNumber).marks.values().stream().reduce(Integer::sum).get();
Вот отправлю я в этот метод аргументом 42, все упадет

2022-12-08 12:04 UTC, shadrina commented on Task_1_4_1/src/main/java/RecordBook.java
> +        }
Тут напрашивается Stream API

2022-12-11 13:51 UTC, Mikhail05Evdokimov commented on Task_1_4_1/src/main/java/RecordBook.java
> +            semesters.get(semesterNumber).marks.values().stream().reduce(Integer::sum).get();
Это приватный метод, в него не может попасть некорректное значение снаружи

2022-12-14 06:56 UTC, shadrina approved these changes

2022-12-17 08:36 UTC, merged